# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site title and description
title:              OAK Docs
description:        Documentation for OAK Blockchain
lang:               en

# Site subpath, e.g. /blog
baseurl:            ""

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink:          /:title/

# Site base hostname & protocol, e.g. http://example.com
url:                ""

# Site logo # e.g. logo.png, upload logo image file to /uploads/ folder
logo:               

navbar:
    sticky:         true
    search:         true
  
# Default author settings
author:
    name:           Chris Li
    title:          CEO
    avatar:         avatar-chris.png

# Author settings, displayed on post and doc pages if front matter references author name e.g. author: peter
authors:
    chris:
      name:         Chris Li
      title:        CEO     
      avatar:       avatar-chris.png
    charles:
      name:         Charles Chen
      title:        Developer    
      avatar:       avatar-xingyou.png
    irsal:
      name:         Irsal McGinnis
      title:        CTO    
      avatar:       avatar-irsal.jpeg
    ryan:
      name:         Ryan Huttman
      title:        Lead Engineer    
      avatar:       avatar-ryan.png
    andrew:
      name:         Andrew Tomaka
      title:        Software Engineer
    laura:
      name:         Laura Reesby
      title:        Software Engineer
      avatar:       avatar-laura.jpeg
    christian:
      name:         Christian Dirk
      title:        Growth Team
    nikhil:
      name:         Nikhil Vengal
      title:        Software Engineer

# Social icons displayed in footer
social:
    email:          chris@oak.tech
    website:        https://oak.tech
    facebook:       
    flickr:
    dribbble:
    github:
    googleplus:
    instagram:      
    linkedin:
    pinterest:
    twitter:        https://twitter.com/oak_network
    vimeo:          
    youtube:        https://www.youtube.com/channel/UCpR12msmm43z46PoAJ1TAiQ

# Share button
share:
    post:           true # Display share buttons on a post page
    doc:            true # Display share buttons on a doc page
    twitter:        username # Enable by adding Twitter handle 
    facebook:       true # Enable by setting true (Facebook handle not required)

# Default footer image settings
footer:
    copyright:      © 2022 OAK Foundation. All rights reserved.

# Disqus comments shortname, requires Disqus account https://disqus.com/
# disqus:
#     shortname:      # 1234

# Google analytics code, get your code here https://www.google.com/analytics/
google_analytics:   G-4BZGDFDJGP

google_analytics_dev:   G-DE2E0J5DNE


# Number of posts displayed on blog page
paginate:           10

# Blog path
# paginate_path:      "/blog/:num/"

# Path to post content assets directory i.e post images, pdfs etc
uploads:            /uploads/

# Build settings
markdown:           kramdown
highlighter:        rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-avatar
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

sass:
  style:            compressed

collections:
  docs:
    output:         true
  faqs:
    output:         false
  changelogs:
    output:         false

# Defaults
defaults:
  # _posts
  - scope:
      path:         ""
      type:         posts
    values:
      layout:       post
  # _docs
  - scope:
      path:         ""
      type:         docs
    values:
      layout:       doc
